Updating the register component. 3 Naming conventions to be updated. …
BuildForSDGCohort2/Team-117-Group-A-Frontend pull request #3
Opened 2020-08-27 19:46 UTC by boneswvb

Updating the register component. 3 Naming conventions to be updated. State and API done

2020-08-30 09:05 UTC, olajohn-ajiboye approved these changes
This looks good, can you please remove the `console.log`😊
One other suggestion is to also use just one changehandle to handle all form input. You can leave as it is because of time.

2020-08-30 09:07 UTC, olajohn-ajiboye requested changes

2020-08-30 09:07 UTC, olajohn-ajiboye commented on src/pages/SignUpPage.js
> +// }
```suggestion

```

2020-08-30 09:07 UTC, olajohn-ajiboye commented on src/pages/SignUpPage.js
> +    console.log('password_confirmation', password_confirmation)
```suggestion

```

2020-08-30 09:07 UTC, olajohn-ajiboye commented on src/pages/SignUpPage.js
> +            console.log(response)
```suggestion

```

2020-08-30 09:07 UTC, olajohn-ajiboye commented on src/pages/SignUpPage.js
> +    //handel change of input for the form
```suggestion
    //handle change of input for the form
```

2020-08-31 15:56 UTC, boneswvb commented
Hi Ola John,

 

I will delete all the stuff you requested.

 

I normally keep them for testing purposes until the component is working properly. I should be able to complete tonight and update to the repo.

 

From: Ola John Ajiboye [mailto:notifications@github.com] 
Sent: Sunday, 30 August 2020 11:08
To: BuildForSDGCohort2/Team-117-Group-A-Frontend
Cc: Wim von Benecke; Author
Subject: Re: [BuildForSDGCohort2/Team-117-Group-A-Frontend] Updating the register component. 3 Naming conventions to be updated. … (#3)

 

@olajohn-ajiboye requested changes on this pull request.

  _____  

In src/pages/SignUpPage.js <https://github.com/BuildForSDGCohort2/Team-117-Group-A-Frontend/pull/3#discussion_r479743585> :

> +// User Signup
 
+// http://moboclinic.herokuapp.com/api/register
 
+
 
+// {
 
+//     "first_name": "segun",
 
+//     "last_name": "aka",
 
+//     "email": "segun@test.com",
 
+//     "phone": "080123456887",
 
+//     "password": "testing"
 
+// }
 

⬇️ Suggested change 

-// User Signup
 
-// http://moboclinic.herokuapp.com/api/register
 
-
 
-// {
 
-//     "first_name": "segun",
 
-//     "last_name": "aka",
 
-//     "email": "segun@test.com",
 
-//     "phone": "080123456887",
 
-//     "password": "testing"
 
-// }
 
  _____  


In src/pages/SignUpPage.js <https://github.com/BuildForSDGCohort2/Team-117-Group-A-Frontend/pull/3#discussion_r479743606> :

> +    console.log('first_name', first_name)
 
+    console.log('last_name', last_name)
 
+    console.log('email', email)
 
+    console.log('phone', phone)
 
+    console.log('password', password)
 
+    console.log('password_confirmation', password_confirmation)
 

⬇️ Suggested change 

-    console.log('first_name', first_name)
 
-    console.log('last_name', last_name)
 
-    console.log('email', email)
 
-    console.log('phone', phone)
 
-    console.log('password', password)
 
-    console.log('password_confirmation', password_confirmation)
 
  _____  


In src/pages/SignUpPage.js <https://github.com/BuildForSDGCohort2/Team-117-Group-A-Frontend/pull/3#discussion_r479743623> :

> +    const handleChangePasswordConfirmation = event => {
 
+        const { name, value } = event.target
 
+        setPasswordConformation({ [name]: value })
 
+    }
 
+
 
+    const onSubmitForm = e => {
 
+        e.preventDefault()
 
+        try {
 
+            const body = { first_name, last_name, email, phone, password }
 
+            const response = fetch('http://moboclinic.herokuapp.com/api/register', {
 
+                method: 'POST',
 
+                headers: { 'Content-Type': 'application/json' },
 
+                body: JSON.stringify(body),
 
+            })
 
+            window.location = '/'
 
+            console.log(response)
 

⬇️ Suggested change 

-            console.log(response)
 
  _____  


In src/pages/SignUpPage.js <https://github.com/BuildForSDGCohort2/Team-117-Group-A-Frontend/pull/3#discussion_r479743633> :

> @@ -0,0 +1,100 @@
 
+import React, { useState } from 'react'
 
+
 
+import SignupForm from '../components/SignupForm/SignupForm'
 
+
 
+const SignUpPage = () => {
 
+    // Form state
 
+    const [first_name, setFirsName] = useState('')
 
+    const [last_name, setLastName] = useState('')
 
+    const [email, setEmail] = useState('')
 
+    const [phone, setPhone] = useState('')
 
+    const [password, setPassword] = useState('')
 
+    const [password_confirmation, setPasswordConformation] = useState('')
 
+
 
+    //handel change of input for the form
 

⬇️ Suggested change 

-    //handel change of input for the form
 
+    //handle change of input for the form
 

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/BuildForSDGCohort2/Team-117-Group-A-Frontend/pull/3#pullrequestreview-478185154> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AHYWVXZWGPDWYJSYY224YG3SDIJFHANCNFSM4QNLIGMQ> .Image removed by sender.

2020-09-01 22:03 UTC, merged